name: reactive_forms_annotations
description: Annotations for reactive_forms_generator
repository: https://github.com/artflutter/reactive_forms_generator

version: 6.0.0-beta.7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  reactive_forms: ^17.0.0
  collection: ^1.18.0
  logging: 1.1.1
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^3.0.2