name: reactive_forms_annotations
description: Annotations for reactive_forms_generator
repository: https://github.com/artflutter/reactive_forms_generator

version: 7.4.3

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  reactive_forms: ^17.0.0
  collection: ^1.18.0
  logging: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0