name: reactive_forms_generator
description: Generator for reactive_forms. Generates form classes based on model.
repository: https://github.com/artflutter/reactive_forms_generator

version: 6.1.1

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  build: ^2.4.2
  source_gen: ^2.0.0
  _fe_analyzer_shared: ^80.0.0
  analyzer: ^7.3.0
  path: ^1.8.1
  build_runner: ^2.4.15
  code_builder: ^4.10.1
  collection: ">=1.0.0 <2.0.0"
  dart_style: ^3.0.1
  recase: ^4.1.0

dev_dependencies:
  build_test: ^2.2.3
  logging: ^1.2.0
  flutter_lints: ^5.0.0

#dependency_overrides:
#  build_resolvers: ^2.1.0
#  test_api: ^0.4.18
#  source_helper: ^1.3.3