name: reactive_forms_generator
description: Generator for reactive_forms. Generates form classes based on model.
repository: https://github.com/artflutter/reactive_forms_generator

version: 7.4.0

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  build: ^4.0.1
  source_gen: ^4.0.1
  _fe_analyzer_shared: ^89.0.0
  analyzer: ^8.2.0
  path: ^1.8.1
  build_runner: ^2.7.0
  code_builder: ^4.10.1
  collection: ">=1.0.0 <2.0.0"
  dart_style: ^3.0.0
  recase: ^4.1.0

dev_dependencies:
  build_test: ^3.4.1
  logging: ^1.2.0
  flutter_lints: ^6.0.0

#dependency_overrides:
#  build_resolvers: ^2.1.0
#  test_api: ^0.4.18
#  source_helper: ^1.3.3