name: PR check [example]
on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr-check-example:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.4
          channel: stable
          cache: true
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: reactive_forms_generator => example => build_runner
        run: cd packages/reactive_forms_generator/example && flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs

      - name: reactive_forms_generator => example => analyze
        run: cd packages/reactive_forms_generator/example && flutter pub get && flutter analyze --no-fatal-infos

      #      - name: reactive_forms_generator => example => code formatting
      #        run: cd packages/reactive_forms_generator/example && flutter pub get && dart format --set-exit-if-changed lib

      - name: reactive_forms_generator => example => test
        run: cd packages/reactive_forms_generator/example && flutter pub get && flutter test