name: PR check [example]
on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr-check-example:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:3.3.10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: reactive_forms_generator => example => build_runner
        run: cd packages/reactive_forms_generator/example && flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs

      - name: reactive_forms_generator => example => analyze
        run: cd packages/reactive_forms_generator/example && flutter pub get && flutter analyze

      - name: reactive_forms_generator => example => code formatting
        run: cd packages/reactive_forms_generator/example && flutter pub get && flutter format --set-exit-if-changed lib

      - name: reactive_forms_generator => example => test
        run: cd packages/reactive_forms_generator/example && flutter pub get && flutter test